### PR TITLE
Merge the safest bits of the changes wanted by plone/meta

### PR DESCRIPTION
**Pull request by ale-rt**
Refs. #58

### CODE REVIEW

**Comment by gforcada** [comment]
I'm not sure if this is worth, I would rather finish #53 I can do it if you are tired of fixing code quality errors 😉

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by ale-rt** [comment]
> I'm not sure if this is worth, I would rather finish #53 I can do it if you are tired of fixing code quality errors wink

It does not harm to have this merged already...

**Review by gforcada — APPROVED** [review]

**Comment by gforcada** [comment]
sorry, it fall through the cracks and I've been sick 🤒 we can merge this if you want to 👍🏾

**Pull request merged**
