### PR TITLE
Do not escape <, >, and & inside script tag

### PR DESCRIPTION
**Pull request by gotcha**
when it is not suppressed.

### CODE REVIEW

**Comment by jensens** [comment]
jenkins pr test started http://jenkins.plone.org/job/pull-request/75/

**Comment by kroman0** [comment]
+1

**Comment by ktarasz** [comment]
+1

**Comment by gotcha** [comment]
Can this PR be merged ?

**Comment by jensens** [comment]
lets see if tests in coredev 4 are green too, PR testing above only checks Plone 5.

**Pull request merged**
