### PR TITLE
Plone meta

### PR DESCRIPTION
**Pull request by ale-rt**

### CODE REVIEW

**Comment by ale-rt** [comment]
I am adding this one just for fun, no real need to merge this one.

I needed to do quite some fixes to make the linting pass and I am giving it up on some files:
https://github.com/plone/Products.PortalTransforms/pull/53/commits/43c02099c84991b581f3a97fcc3f00c8e4ead107

E.g. I had to disable the `codespell` checker for CHANGES.rst to prevent that this line:
```
Fixed non critical typo in error message: Unvalid -> Invalid [tiran]
```
breaks it...
Also I decided to skip zpretty and code spell in the tests folder.

If we do not want to risk such a big PR, some trivial changes can be merged already.
I will maybe add more "sub PRs".

**Comment by ale-rt** [comment]
@jenkins-plone-org please run jobs

**Comment by gforcada** [comment]
For `codespell` you can rework the sentence to:

`Fixed non critical typo in error message [tiran]`

It's a changelog entry, and something old at it, so I don't think anyone will complain about it 😅 

As for too much code analysis errors... there is `autoflake8` that might help a bit... but if we want to enable workflows on GHA and ensure our codebase is fine and sound, we have to go through the hurdle of cleaning it up 🦾 🤖

**Comment by gforcada** [comment]
Let's use #55 to track `plone/meta` integration in this repository 👍🏾

**Pull request closed without merging**
