### PR TITLE
Fixed regular expression in tests on Python 3.11.

### PR DESCRIPTION
**Pull request by mauritsvanrees**
This fixes https://github.com/plone/Products.PortalTransforms/issues/48

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
I was missing a fix from master, rebased now.

@jenkins-plone-org please run jobs

**Comment by mauritsvanrees** [comment]
All green, except Python 3.11, which needs fixes in two other packages. A failure in this job is no problem, this can be merged.

**Review by davisagli — APPROVED** [review]

**Pull request merged**
