### PR TITLE
Fix removed `unittest.makeSuite` in python 3.13

### PR DESCRIPTION
**Pull request by petschki**

### CODE REVIEW

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Review by mauritsvanrees — CHANGES_REQUESTED** [review]
I would undo the change to the demo files.  Or edit `input/demo1.pdf` and fix the code in there as well.  Otherwise this input does not match the expected output in the changed `output/demo1.html`.

This part of the tests likely gets ignored because the `pdftohtml` binary is not installed.  If someone *does* have it installed, it will give an error now.

**Comment by petschki** [comment]
Ah thanks for the tip. I wondered why I got an error on my Mac but not on Jenkins. Will change 👍🏼

**Comment by petschki** [comment]
@jenkins-plone-org please run jobs

**Pull request merged**
