### PR TITLE
Removed CMFDefault dependency

### PR DESCRIPTION
**Pull request by tomgross**

### CODE REVIEW

**Comment by prakharjoshi** [comment]
@tomgross Here is what I have been working on this helps removing the extra "div" tag in the beggining and end of the result. https://gist.github.com/prakharjoshi/16d593cee21801e0b91b . I have been working on to create a more appropriate script which passes more and more test cases.
Also we can now remove SGMLParse and ScrubHTML classes as these classes have CMFDeault dependencies, right ?

**Comment by gforcada** [comment]
#6

**Comment by prakharjoshi** [comment]
@gforcada  also for stripingParser class and scrubhtml method we can use the cleaner class form http://lxml.de/api/lxml.html.clean-pysrc.html#Cleaner

**Comment by tisto** [comment]
http://jenkins.plone.org/job/pull-request/172/

**Pull request merged**
