### PR TITLE
Correcting Typo errors in user manual

### PR DESCRIPTION
**Pull request by prakharjoshi**
There were few typo errors in the user manual of the product.

### CODE REVIEW

**Comment by gforcada** [comment]
@prakharjoshi for making changes on repositories on plone github organization you should sign the contributors agreement: https://plone.org/foundation/contributors-agreement once that's done it can be merged.

**Comment by mauritsvanrees** [comment]
@esteele This simply fixes two typos in documentation. Is it alright with you as release manager to merge this?

Looks good to me.

**Comment by prakharjoshi** [comment]
@gforcada  Now I have signed the agreement :)

**Comment by mauritsvanrees** [comment]
@prakharjoshi Awesome, welcome to the club! :-) I see you in the Plone team indeed. I have merged the pull request. Thanks for your contribution. I will release it shortly.

**Comment by prakharjoshi** [comment]
@mauritsvanrees  Thanks. I am enjoying working year since this summer :)

**Comment by mauritsvanrees** [comment]
2.1.8 released.

**Pull request merged**
